# .github/workflows/network_viz.yml

name: Generate Network Visualization # 워크플로우 이름 구분

on:
  workflow_dispatch: # 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # 만약을 위해 유지 (NetworkX 등 다른 라이브러리가 필요로 할 수도 있음)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements.txt 는 두 워크플로우에 필요한 모든 라이브러리를 포함해야 함
          pip install -r requirements.txt

      - name: Generate network visualization
        # 네트워크 시각화 스크립트 실행
        run: python generate_network_viz.py # 이 스크립트는 grouped_keywords.json 사용

      - name: Commit and push network viz image
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Update network visualization image [skip ci]"
          file_pattern: "output/network_viz.png" # 네트워크 시각화 이미지 경로
          skip_fetch: true
          skip_dirty_check: false
